# Site settings
title: Terry's First Blog
email: busyguys@me.com
description: > # this means to ignore newlines until "baseurl:"
  Testing the blogs
baseurl: "" # the subpath of your site, e.g. /blog/
url: "http://busyguys.github.io" # the base hostname & protocol for your site
github_username:  busyguys

# Build settings
markdown: kramdown
